from pathlib import Path

TOOLS_DIR = Path("agent/generated_tools")
REPORT = Path("reports/toolmaking_report.md")


def ensure_tools_dir():
    TOOLS_DIR.mkdir(parents=True, exist_ok=True)


def create_tool_if_needed(tool_name: str, purpose: str):
    ensure_tools_dir()
    target = TOOLS_DIR / f"{tool_name}.py"

    if target.exists():
        REPORT.write_text(f"# Toolmaking Report\n\n- Tool already exists: {target}\n")
        return False, str(target)

    content = f'''"""Autogenerated helper tool.
Purpose: {purpose}
"""


def run():
    return {{"tool": "{tool_name}", "purpose": "{purpose}", "status": "placeholder"}}


if __name__ == "__main__":
    print(run())
'''
    target.write_text(content)
    REPORT.write_text(f"# Toolmaking Report\n\n- Created tool: {target}\n- Purpose: {purpose}\n")
    return True, str(target)


if __name__ == "__main__":
    create_tool_if_needed("sample_helper", "Demonstrate autonomous tool creation")
